# <center>Performance Comparison of Machine Learning Algorithms in Healthcare Diseases Conditions<br><br>(Raw Data to ML Data)<center>

### <center>Chan Soraneat Chanthan<br>001194686<br>Supervisor: Dr. Ik Soo Lim<center>

### Below represent two main parts:
1. Feature Selection
2. Data Adjustment

# 1. Feature Selection

## Loading Original Dataset

In [1]:
# Import all the needed packages
import pandas as pd
import numpy as np

In [2]:
# Read the csv file dataset and set as brfss2020 
brfss2020 = pd.read_csv("OriginalRawData.csv")

In [3]:
# Display the shape of the entire dataset
brfss2020.shape

(401958, 279)

In [6]:
# Check all column in the data
pd.set_option('display.max_columns', 500)
brfss2020.head()

_STATE  FMONTH    IDATE  IMONTH  IDAY  IYEAR  DISPCODE       SEQNO  \
0     1.0     1.0  1042020       1     4   2020    1100.0  2020000001   
1     1.0     1.0  2072020       2     7   2020    1200.0  2020000002   
2     1.0     1.0  1232020       1    23   2020    1100.0  2020000003   
3     1.0     1.0  1092020       1     9   2020    1100.0  2020000004   
4     1.0     1.0  1042020       1     4   2020    1100.0  2020000005   

           _PSU  CTELENM1  PVTRESD1  COLGHOUS  STATERE1  CELPHONE  LADULT1  \
0  2.020000e+09       1.0       1.0       NaN       1.0       2.0      1.0   
1  2.020000e+09       1.0       1.0       NaN       1.0       2.0      1.0   
2  2.020000e+09       1.0       1.0       NaN       1.0       2.0      1.0   
3  2.020000e+09       1.0       1.0       NaN       1.0       2.0      1.0   
4  2.020000e+09       1.0       1.0       NaN       1.0       2.0      1.0   

   COLGSEX  NUMADULT  LANDSEX  NUMMEN  NUMWOMEN  RESPSLCT  SAFETIME  CTELNUM1  \
0      NaN       1.0      2.0     0.0       1.0       NaN       NaN       NaN   
1      NaN       1.0      2.0     0.0       1.0       NaN       NaN       NaN   
2      NaN       1.0      2.0     0.0       1.0       NaN       NaN       NaN   
3      NaN       1.0      2.0     0.0       1.0       NaN       NaN       NaN   
4      NaN       1.0      2.0     0.0       1.0       NaN       NaN       NaN   

   CELLFON5  CADULT1  CELLSEX  PVTRESD3  CCLGHOUS  CSTATE1  LANDLINE  HHADULT  \
0       NaN      NaN      NaN       NaN       NaN      NaN       NaN      NaN   
1       NaN      NaN      NaN       NaN       NaN      NaN       NaN      NaN   
2       NaN      NaN      NaN       NaN       NaN      NaN       NaN      NaN   
3       NaN      NaN      NaN       NaN       NaN      NaN       NaN      NaN   
4       NaN      NaN      NaN       NaN       NaN      NaN       NaN      NaN   

   SEXVAR  GENHLTH  PHYSHLTH  MENTHLTH  POORHLTH  HLTHPLN1  PERSDOC2  MEDCOST  \
0     2.0      2.0       3.0      30.0       3.0       2.0       3.0      1.0   
1     2.0      3.0      88.0      88.0       NaN       1.0       1.0      1.0   
2     2.0      3.0      88.0      88.0       NaN       1.0       1.0      2.0   
3     2.0      1.0      88.0      88.0       NaN       1.0       3.0      2.0   
4     2.0      2.0      88.0      88.0       NaN       1.0       1.0      2.0   

   CHECKUP1  EXERANY2  SLEPTIM1  CVDINFR4  CVDCRHD4  CVDSTRK3  ASTHMA3  \
0       4.0       1.0       5.0       2.0       2.0       2.0      1.0   
1       1.0       1.0       7.0       2.0       2.0       2.0      1.0   
2       1.0       1.0       7.0       2.0       2.0       2.0      2.0   
3       2.0       2.0       6.0       2.0       2.0       2.0      2.0   
4       1.0       1.0       7.0       2.0       2.0       1.0      2.0   

   ASTHNOW  CHCSCNCR  CHCOCNCR  CHCCOPD2  HAVARTH4  ADDEPEV3  CHCKDNY2  \
0      1.0       1.0       1.0       1.0       1.0       1.0       2.0   
1      2.0       2.0       2.0       2.0       1.0       1.0       2.0   
2      NaN       2.0       1.0       2.0       1.0       2.0       2.0   
3      NaN       2.0       2.0       2.0       2.0       2.0       2.0   
4      NaN       2.0       2.0       2.0       2.0       2.0       2.0   

   DIABETE4  DIABAGE3  LASTDEN4  RMVTETH4  MARITAL  EDUCA  RENTHOM1  NUMHHOL3  \
0       1.0      35.0       1.0       2.0      2.0    6.0       1.0       2.0   
1       3.0       NaN       1.0       1.0      3.0    6.0       1.0       1.0   
2       3.0       NaN       1.0       7.0      1.0    5.0       1.0       2.0   
3       3.0       NaN       7.0       1.0      3.0    4.0       1.0       9.0   
4       3.0       NaN       7.0       8.0      3.0    6.0       2.0       2.0   

   NUMPHON3  CPDEMO1B  VETERAN3  EMPLOY1  CHILDREN  INCOME2  PREGNANT  \
0       NaN       1.0       2.0      4.0      88.0      1.0       NaN   
1       1.0       1.0       2.0      7.0      88.0     99.0       NaN   
2       NaN       1.0       2.0      7

## Feature Selection

In [8]:
# Select the four diseases and related features
brfss = brfss2020[['DIABETE4', 'CHCKDNY2','CVDCRHD4', 'ASTHMA3', 'CVDSTRK3', '_MICHD', 'CHCSCNCR', '_BMI5', 'SMOKE100', 
                   '_TOTINDA', '_RFDRHV7', 'HLTHPLN1', 'MEDCOST', 'GENHLTH', 'MENTHLTH', 'PHYSHLTH', 'DIFFWALK', '_SEX', 
                   '_AGEG5YR', 'EDUCA', 'INCOME2' ]]

In [9]:
# Display the shape of data after the feature selection
brfss.shape

(401958, 21)

In [10]:
# Display the first 5 rows of the dataset
brfss.head(5)

DIABETE4  CHCKDNY2  CVDCRHD4  ASTHMA3  CVDSTRK3  _MICHD  CHCSCNCR   _BMI5  \
0       1.0       2.0       2.0      1.0       2.0     2.0       1.0  1660.0   
1       3.0       2.0       2.0      1.0       2.0     2.0       2.0  2918.0   
2       3.0       2.0       2.0      2.0       2.0     2.0       2.0     NaN   
3       3.0       2.0       2.0      2.0       2.0     2.0       2.0     NaN   
4       3.0       2.0       2.0      2.0       1.0     2.0       2.0  2034.0   

   SMOKE100  _TOTINDA  _RFDRHV7  HLTHPLN1  MEDCOST  GENHLTH  MENTHLTH  \
0       1.0       1.0       1.0       2.0      1.0      2.0      30.0   
1       NaN       1.0       9.0       1.0      1.0      3.0      88.0   
2       2.0       1.0       1.0       1.0      2.0      3.0      88.0   
3       2.0       2.0       1.0       1.0      2.0      1.0      88.0   
4       2.0       1.0       1.0       1.0      2.0      2.0      88.0   

   PHYSHLTH  DIFFWALK  _SEX  _AGEG5YR  EDUCA  INCOME2  
0       3.0       2.0   2.0       8.0    6.0      1.0  
1      88.0       2.0   2.0      10.0    6.0     99.0  
2      88.0       2.0   2.0      10.0    5.0      7.0  
3      88.0       2.0   2.0      13.0    4.0     99.0  
4      88.0       2.0   2.0      13.0    6.0     77.0

# 2. Data Adjustment

## Adjustment the Data Variables in each Features

In [16]:
# Upgrade the data for suitable in ML study
# DIABETE4 = Diabetes disease
# 1 is for yes diabetes
# Change the variable of 2 (only during pregnancy), 3 (no diabetes) and 4 (pre-diabetes or borderline diabetes) to 0
# Remove the variables of 7 (dont knows) and 9 (refused)
brfss['DIABETE4'] = brfss['DIABETE4'].replace({2:0, 3:0, 4:0})
brfss = brfss[brfss.DIABETE4 != 7]
brfss = brfss[brfss.DIABETE4 != 9]
# Display the variable in DIABETE4 after upgrade
brfss.DIABETE4.unique()

array([ 1.,  0., nan])

In [17]:
# Upgrade the data for suitable in ML study
# CHCKDNY2 = Kidney disease
# 1 is for yes kidney diseases
# Change the variable of 2 (no kidney disease) to 0
# Remove the variables of 7 (dont knows) and 9 (refused)
brfss['CHCKDNY2'] = brfss['CHCKDNY2'].replace({2:0})
brfss = brfss[brfss.CHCKDNY2 != 7]
brfss = brfss[brfss.CHCKDNY2 != 9]
# Display the variable in CHCKDNY2 after upgrade
brfss.CHCKDNY2.unique()

array([ 0.,  1., nan])

In [20]:
# Upgrade the data for suitable in ML study
# ASTHMA3 = Asthma disease
# 1 is for yes asthma diseases
# Change the variable of 2 (no asthma disease) to 0
brfss['ASTHMA3'] = brfss['ASTHMA3'].replace({2:0})
brfss = brfss[brfss.ASTHMA3 != 7]
brfss = brfss[brfss.ASTHMA3 != 9]
# Display the variable in ASTHMA3 after upgrade
brfss.ASTHMA3.unique()

array([ 1.,  0., nan])

In [19]:
# Upgrade the data for suitable in ML study
# CVDCRHD4 = Heart disease
# 1 is for yes heart diseases
# Change the variable of 2 (no heart disease) to 0
# Remove the variables of 7 (dont knows) and 9 (refused)
brfss['CVDCRHD4'] = brfss['CVDCRHD4'].replace({2:0})
brfss = brfss[brfss.CVDCRHD4 != 7]
brfss = brfss[brfss.CVDCRHD4 != 9]
# Display the variable in CVDCRHD4 after upgrade
brfss.CVDCRHD4.unique()

array([ 0.,  1., nan])

In [21]:
# Upgrade the data for suitable in ML study
# CVDSTRK3 = Stroke
# 1 is for yes stroke
# Change the variable of 2 (no stroke) to 0
# Remove the variables of 7 (dont knows) and 9 (refused)
brfss['CVDSTRK3'] = brfss['CVDSTRK3'].replace({2:0})
brfss = brfss[brfss.CVDSTRK3 != 7]
brfss = brfss[brfss.CVDSTRK3 != 9]
# Display the variable in CVDSTRK3 after upgrade
brfss.CVDSTRK3.unique()

array([ 0.,  1., nan])

In [22]:
# Upgrade the data for suitable in ML study
# _MICHD = Heart attack
# 1 is for yes heart attack
# Change the variable of 2 (no heart attack) to 0
brfss['_MICHD'] = brfss['_MICHD'].replace({2: 0})
# Display the variable in _MICHD after upgrade
brfss._MICHD.unique()

array([ 0.,  1., nan])

In [24]:
# Upgrade the data for suitable in ML study
# CHCSCNCR = Skin cancer
# 1 is for yes skin cancer
# Change the variable of 2 (no skin cancer) to 0
# Remove the variables of 7 (dont knows) and 9 (refused)
brfss['CHCSCNCR'] = brfss['CHCSCNCR'].replace({2:0})
brfss = brfss[brfss.CHCSCNCR != 7]
brfss = brfss[brfss.CHCSCNCR != 9]
# Display the variable in CHCSCNCR after upgrade
brfss.CHCSCNCR.unique()

array([ 1.,  0., nan])

In [25]:
# Upgrade the data for suitable in ML study
# _BMI5 = Body mass index
# Change the variable by BMI / 100. Exp: BMI of 1023 is really 10.23 
brfss['_BMI5'] = brfss['_BMI5'].div(100).round(0)
# Display the variable in _BMI5 after upgrade
brfss._BMI5.unique()

array([17., 29., nan, 20., 27., 24., 22., 32., 26., 41., 34., 28., 23.,
       30., 18., 21., 25., 37., 31., 45., 19., 39., 33., 47., 40., 35.,
       44., 36., 59., 38., 43., 49., 42., 53., 52., 15., 55., 50., 56.,
       76., 16., 57., 48., 46., 51., 12., 14., 60., 67., 63., 66., 54.,
       64., 13., 58., 62., 83., 81., 68., 61., 69., 73., 90., 72., 79.,
       71., 82., 75., 77., 70., 65., 87., 80., 84., 78., 74., 86., 85.,
       93., 94., 92., 95., 89., 98., 88.])

In [26]:
# Upgrade the data for suitable in ML study
# SMOKE100 = Smoke
# 1 is for yes smoke 100 cigarettes
# Change the variable of 2 (no smoke 100 cigarettes) to 0
# Remove the variables of 7 (dont knows) and 9 (refused)
brfss['SMOKE100'] = brfss['SMOKE100'].replace({2:0})
brfss = brfss[brfss.SMOKE100 != 7]
brfss = brfss[brfss.SMOKE100 != 9]
# Display the variable in SMOKE100 after upgrade
brfss.SMOKE100.unique()

array([ 1., nan,  0.])

In [27]:
# Upgrade the data for suitable in ML study
# _TOTINDA = Physical activity
# 1 is for yes physical activity
# Change the variable of 2 (no physical activity) to 0
# Remove the variables of 9 (dont knows/refused)
brfss['_TOTINDA'] = brfss['_TOTINDA'].replace({2:0})
brfss = brfss[brfss._TOTINDA != 9]
# Display the variable in _TOTINDA after upgrade
brfss._TOTINDA.unique()

array([1., 0.])

In [28]:
# Upgrade the data for suitable in ML study
# _RFDRHV7 = Heavy alcohol consumption
# Change the variable of 1 (no heavy alcohol consumption) to 0
# Change the variable of 2 (yes heavy alcohol consumption) to 1
# Remove the variables of 9 (dont knows/refused)
brfss['_RFDRHV7'] = brfss['_RFDRHV7'].replace({1:0, 2:1})
brfss = brfss[brfss._RFDRHV7 != 9]
# Display the variable in _RFDRHV7 after upgrade
brfss._RFDRHV7.unique()

array([0., 1.])

In [29]:
# Upgrade the data for suitable in ML study
# HLTHPLN1 = Healthcare coverage
# 1 is for yes healthcare coverage
# Change the variable of 2 (no healthcare coverage) to 0
# Remove the variables of 7 (dont knows) and 9 (refused)
brfss['HLTHPLN1'] = brfss['HLTHPLN1'].replace({2:0})
brfss = brfss[brfss.HLTHPLN1 != 7]
brfss = brfss[brfss.HLTHPLN1 != 9]
# Display the variable in HLTHPLN1 after upgrade
brfss.HLTHPLN1.unique()

array([0., 1.])

In [31]:
# Upgrade the data for suitable in ML study
# MEDCOST = No medical cost
# 1 is for yes that no medical cost
# Change the variable of 2 (no that no medical cost) to 0
# Remove the variables of 7 (dont knows) and 9 (refused)
brfss['MEDCOST'] = brfss['MEDCOST'].replace({2:0})
brfss = brfss[brfss.MEDCOST != 7]
brfss = brfss[brfss.MEDCOST != 9]
# Display the variable in MEDCOST after upgrade
brfss.MEDCOST.unique()

array([1., 0.])

In [32]:
# Upgrade the data for suitable in ML study
# GENHLTH = General health
# No change in this feature, while 1 to 5 is Excellent to Poor
# Remove the variables of 7 (dont knows) and 9 (refused)
brfss = brfss[brfss.GENHLTH != 7]
brfss = brfss[brfss.GENHLTH != 9]
# Display the variable in GENHLTH after upgrade
brfss.GENHLTH.unique()

array([ 2.,  3.,  1.,  4.,  5., nan])

In [33]:
# Upgrade the data for suitable in ML study
# MENTHLTH = Mental health
# 1 to 30 is the amount of day that have bad mental health
# Change the variable of 88 (no bad mental health) to 0
# Remove the variables of 77 (dont knows) and 99 (refused)
brfss['MENTHLTH'] = brfss['MENTHLTH'].replace({88:0})
brfss = brfss[brfss.MENTHLTH != 77]
brfss = brfss[brfss.MENTHLTH != 99]
# Display the variable in MENTHLTH after upgrade
brfss.MENTHLTH.unique()

array([30.,  0.,  2.,  5., 15.,  8.,  4.,  3., 10., 14., 20.,  1.,  7.,
       24.,  9., 28., 16., 12.,  6., 25., 17., 18., 21., 29., 22., 13.,
       23., 27., 26., 11., 19., nan])

In [34]:
# Upgrade the data for suitable in ML study
# PHYSHLTH = Physical health
# 1 to 30 is the amount of day that have bad physical health
# Change the variable of 88 (no bad physical health) to 0
# Remove the variables of 77 (dont knows) and 99 (refused)
brfss['PHYSHLTH'] = brfss['PHYSHLTH'].replace({88:0})
brfss = brfss[brfss.PHYSHLTH != 77]
brfss = brfss[brfss.PHYSHLTH != 99]
# Display the variable in PHYSHLTH after upgrade
brfss.PHYSHLTH.unique()

array([ 3.,  0., 20., 28.,  6., 15.,  5., 30.,  7.,  1.,  2., 21.,  4.,
       10., 14., 18.,  8., 25., 16., 29., 27., 17., 24., 12., 23., 26.,
       22., 19.,  9., 13., 11., nan])

In [35]:
# Upgrade the data for suitable in ML study
# DIFFWALK = Difficulty walking
# 1 is for yes difficulty walking
# Change the variable of 2 (no difficulty walking) to 0
# Remove the variables of 7 (dont knows) and 9 (refused)
brfss['DIFFWALK'] = brfss['DIFFWALK'].replace({2:0})
brfss = brfss[brfss.DIFFWALK != 7]
brfss = brfss[brfss.DIFFWALK != 9]
# Display the variable in DIFFWALK after upgrade
brfss.DIFFWALK.unique()

array([ 0.,  1., nan])

In [36]:
# Upgrade the data for suitable in ML study
# _SEX = Sex
# 1 is for yes male
# Change the variable of 2 (female) to 0
brfss['_SEX'] = brfss['_SEX'].replace({2:0})
# Display the variable in _SEX after upgrade
brfss._SEX.unique()

array([0., 1.])

In [37]:
# Upgrade the data for suitable in ML study
# _AGEG5YR = Age
# No change in this feature, while 1 to 13 is the variable of each age group
# Remove the variables of 14 (dont knows/refused)
brfss = brfss[brfss._AGEG5YR != 14]
# Display the variable in _AGEG5YR after upgrade
brfss._AGEG5YR.unique()

array([ 8., 10., 13., 12.,  5., 11.,  9.,  7.,  6.,  1.,  4.,  2.,  3.])

In [38]:
# Upgrade the data for suitable in ML study
# EDUCA = Education
# No change in this feature, while 1 to 6 is the variable of education level
# Remove the variables of 9 (dont knows/refused)
brfss = brfss[brfss.EDUCA != 9]
# Display the variable in EDUCA after upgrade
brfss.EDUCA.unique()

array([6., 5., 4., 2., 3., 1.])

In [39]:
# Upgrade the data for suitable in ML study
# INCOME2 = Income
# No change in this feature, while 1 to 8 is the variable of annual income level
# Remove the variables of 77 (dont knows) and 99 (refused)
brfss = brfss[brfss.INCOME2 != 77]
brfss = brfss[brfss.INCOME2 != 99]
# Display the variable in INCOME2 after upgrade
brfss.INCOME2.unique()

array([ 1.,  7.,  5.,  6.,  4.,  2.,  8.,  3., nan])

In [40]:
# Display the shape of the data after the adjustment
brfss.shape

(288306, 21)

In [41]:
# Display the first 5 rows of the dataset
brfss.head()

DIABETE4  CHCKDNY2  CVDCRHD4  ASTHMA3  CVDSTRK3  _MICHD  CHCSCNCR  _BMI5  \
0       1.0       0.0       0.0      1.0       0.0     0.0       1.0   17.0   
2       0.0       0.0       0.0      0.0       0.0     0.0       0.0    NaN   
5       1.0       0.0       0.0      1.0       0.0     0.0       0.0   27.0   
6       0.0       0.0       0.0      0.0       0.0     0.0       1.0   24.0   
8       0.0       0.0       0.0      0.0       0.0     0.0       0.0   24.0   

   SMOKE100  _TOTINDA  _RFDRHV7  HLTHPLN1  MEDCOST  GENHLTH  MENTHLTH  \
0       1.0       1.0       0.0       0.0      1.0      2.0      30.0   
2       0.0       1.0       0.0       1.0      0.0      3.0       0.0   
5       1.0       1.0       0.0       1.0      0.0      4.0      30.0   
6       0.0       0.0       0.0       1.0      0.0      3.0       0.0   
8       0.0       1.0       0.0       1.0      0.0      2.0       0.0   

   PHYSHLTH  DIFFWALK  _SEX  _AGEG5YR  EDUCA  INCOME2  
0       3.0       0.0   0.0       8.0    6.0      1.0  
2       0.0       0.0   0.0      10.0    5.0      7.0  
5      20.0       0.0   1.0      10.0    4.0      5.0  
6       0.0       0.0   0.0      12.0    4.0      6.0  
8      28.0       1.0   0.0       5.0    6.0      6.0

## Rename the Features

In [42]:
# Rename the features
BRFSS = brfss.rename(columns = {'DIABETE4':'Diabetes', 'CHCKDNY2':'Kidney', 'CVDCRHD4':'HeartDisease', 'ASTHMA3':'Asthma', 
                                'CVDSTRK3':'Stroke', '_MICHD':'HeartAttack', 'CHCSCNCR':'SkinCancer', '_BMI5':'BMI', 
                                'SMOKE100':'Smoke', '_TOTINDA':'PhysActivity', '_RFDRHV7':'HvyAlcoholConsump', 'HLTHPLN1':'HlthCov', 
                                'MEDCOST':'NoMedCost', 'GENHLTH':'GenHlth', 'MENTHLTH':'MentHlth', 'PHYSHLTH':'PhysHlth', 
                                'DIFFWALK':'DiffWalk', '_SEX':'Sex', '_AGEG5YR':'Age', 'EDUCA':'Age', 'INCOME2':'Income' })

In [43]:
# Display the first 5 rows of the dataset
BRFSS.head()

Diabetes  Kidney  HeartDisease  Asthma  Stroke  HeartAttack  SkinCancer  \
0       1.0     0.0           0.0     1.0     0.0          0.0         1.0   
2       0.0     0.0           0.0     0.0     0.0          0.0         0.0   
5       1.0     0.0           0.0     1.0     0.0          0.0         0.0   
6       0.0     0.0           0.0     0.0     0.0          0.0         1.0   
8       0.0     0.0           0.0     0.0     0.0          0.0         0.0   

    BMI  Smoke  PhysActivity  HvyAlcoholConsump  HlthCov  NoMedCost  GenHlth  \
0  17.0    1.0           1.0                0.0      0.0        1.0      2.0   
2   NaN    0.0           1.0                0.0      1.0        0.0      3.0   
5  27.0    1.0           1.0                0.0      1.0        0.0      4.0   
6  24.0    0.0           0.0                0.0      1.0        0.0      3.0   
8  24.0    0.0           1.0                0.0      1.0        0.0      2.0   

   MentHlth  PhysHlth  DiffWalk  Sex   Age  Age  Income  
0      30.0       3.0       0.0  0.0   8.0  6.0     1.0  
2       0.0       0.0       0.0  0.0  10.0  5.0     7.0  
5      30.0      20.0       0.0  1.0  10.0  4.0     5.0  
6       0.0       0.0       0.0  0.0  12.0  4.0     6.0  
8       0.0      28.0       1.0  0.0   5.0  6.0     6.0

In [45]:
# Save the dataframe as a new csv file
BRFSS.to_csv('BRFSS2020(21features).csv', sep=",", index=False)